version: '2.1'
services:

  ### Application Code Container

  egj2021:
    container_name: egj_app
    #you can comment out the next line
    restart: always
    build: .
    image: egj/egj2021_app
    ports:
      # change the local-port
      # [local-ip]:[local-port]:[container-port]
      - "127.0.0.1:8333:80"